# Generated by Django 5.2.5 on 2026-08-04 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('sales_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commission_settlements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlements', to='core.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='unique_employee_commission_settlement_per_period')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plans', to='core.employee')),
            ],
            options={
                'ordering': ['-valid_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='employee_commission_percentage_between_0_and_100')],
            },
        ),
    ]
