# Generated by Django 5.2.5 on 2026-08-17 16:11

from django.db import migrations
from django.db.models import F, Sum


def resolve_product_stock(*, product_id, product_stock, variant_stock):
    """Resolve only unambiguous historical representations of stock."""
    if product_stock == 0:
        return variant_stock

    raise RuntimeError(
        'No se pueden eliminar variantes: el producto '
        f'{product_id} tiene stock propio no nulo {product_stock} y sus variantes '
        f'suman {variant_stock}. No es posible determinar si el stock del '
        'producto es un agregado, inventario independiente o un valor '
        'desactualizado. Corrija o migre esos datos antes de continuar.'
    )


def consolidate_variant_inventory(apps, schema_editor):
    """Protect historical links and preserve total units on Product."""
    Product = apps.get_model('core', 'Product')
    ProductVariant = apps.get_model('core', 'ProductVariant')
    StockMovement = apps.get_model('core', 'StockMovement')
    TransactionDetail = apps.get_model('core', 'TransactionDetail')

    mismatched_details = (
        TransactionDetail.objects
        .filter(variant__isnull=False)
        .exclude(
            product_id=F('variant__variant_type__product_id'),
        )
        .count()
    )
    mismatched_movements = (
        StockMovement.objects
        .filter(variant__isnull=False)
        .exclude(
            product_id=F('variant__variant_type__product_id'),
        )
        .count()
    )

    if mismatched_details or mismatched_movements:
        raise RuntimeError(
            'No se pueden eliminar variantes: existen '
            f'{mismatched_details} detalles de transacción y '
            f'{mismatched_movements} movimientos de stock cuya variante '
            'no pertenece al producto asociado.'
        )

    variant_totals = (
        ProductVariant.objects
        .values('variant_type__product_id')
        .annotate(total_stock=Sum('stock'))
    )

    for row in variant_totals.iterator():
        product = Product.objects.get(
            pk=row['variant_type__product_id'],
        )
        resolved_stock = resolve_product_stock(
            product_id=product.pk,
            product_stock=product.stock,
            variant_stock=row['total_stock'],
        )

        if product.stock != resolved_stock:
            Product.objects.filter(pk=product.pk).update(
                stock=resolved_stock,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            consolidate_variant_inventory,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_type',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productvarianttype',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvarianttype',
            name='status',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='core_stockm_variant_0935f7_idx',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantType',
        ),
    ]
