# Generated by Django 5.2.5 on 2026-08-18 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def validate_existing_debts(apps, schema_editor):
    Debt = apps.get_model("core", "Debt")
    invalid_counts = {
        "total_amount_nonpositive": Debt.objects.filter(
            total_amount__lte=0,
        ).count(),
        "paid_amount_negative": Debt.objects.filter(
            paid_amount__lt=0,
        ).count(),
        "paid_amount_above_total": Debt.objects.filter(
            paid_amount__gt=models.F("total_amount"),
        ).count(),
        "settled_with_outstanding_balance": Debt.objects.filter(
            is_settled=True,
            paid_amount__lt=models.F("total_amount"),
        ).count(),
        "unsettled_without_balance": Debt.objects.filter(
            is_settled=False,
            paid_amount=models.F("total_amount"),
        ).count(),
    }
    invalid_counts = {
        name: count
        for name, count in invalid_counts.items()
        if count
    }
    if invalid_counts:
        summary = ", ".join(
            f"{name}={count}"
            for name, count in sorted(invalid_counts.items())
        )
        raise RuntimeError(
            "No se pueden aplicar las constraints de Debt porque existen "
            f"datos incompatibles ({summary}). Ejecute "
            "`python manage.py diagnose_financial_integrity` y corrija "
            "los datos mediante un procedimiento auditado antes de reintentar."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_productvariant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            validate_existing_debts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='debt',
            name='debt_total_amount_gte_0',
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='debt_total_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_settled', True), ('paid_amount', models.F('total_amount'))), models.Q(('is_settled', False), ('paid_amount__lt', models.F('total_amount'))), _connector='OR'), name='debt_settlement_matches_paid_amount'),
        ),
    ]
