# Generated by Django 5.2.5 on 2026-08-04 21:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commissionsettlement_employeecommissionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('deposit', 'Depósito en caja'), ('withdrawal', 'Retiro de caja'), ('employee_advance', 'Adelanto a empleado'), ('employee_repayment', 'Devolución de adelanto'), ('other_income', 'Otro ingreso'), ('other_expense', 'Otro egreso')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-open_time']},
        ),
        migrations.AddField(
            model_name='cashregister',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='closing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashregister',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='expected_closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='opening_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='open_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['business', 'method_type'], name='paymethod_biz_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='cash_register_opening_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.CheckConstraint(condition=models.Q(('closing_balance__isnull', True), ('closing_balance__gte', 0), _connector='OR'), name='cash_register_closing_balance_gte_0'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.cashregister'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='core.employee'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='core.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['cash_register', 'created_at'], name='cashmov_register_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['employee', 'created_at'], name='cashmov_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='cashmov_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_movement_amount_gt_0'),
        ),
    ]
