# Generated by Django 5.2.5 on 2026-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cashmovement_alter_cashregister_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsettlement',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='commissionsettlement',
            name='employee_advances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='commissionsettlement',
            name='employee_repayments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='commissionsettlement',
            name='net_commission_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='commissionsettlement',
            name='remaining_advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('employee_advances__gte', 0)), name='commission_employee_advances_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('employee_repayments__gte', 0)), name='commission_employee_repayments_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('advance_balance__gte', 0)), name='commission_advance_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('net_commission_payable__gte', 0)), name='commission_net_payable_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_advance_balance__gte', 0)), name='commission_remaining_advance_gte_0'),
        ),
    ]
