# Generated by Django 5.2.5 on 2026-08-05 17:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commissionsettlement_advance_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('closed', 'Cerrado'), ('reopened', 'Reabierto')], default='closed', max_length=20)),
                ('summary', models.JSONField()),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closures', to='core.business')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_monthly_periods', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_monthly_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-version'],
                'indexes': [models.Index(fields=['business', 'year', 'month'], name='monthclose_biz_period_idx'), models.Index(fields=['business', 'status'], name='monthclose_biz_status_idx'), models.Index(fields=['closed_at'], name='monthclose_closed_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'year', 'month', 'version'), name='unique_monthly_closure_version'), models.UniqueConstraint(condition=models.Q(('status', 'closed')), fields=('business', 'year', 'month'), name='one_active_monthly_closure'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthly_closure_month_1_12'), models.CheckConstraint(condition=models.Q(('year__gte', 2000)), name='monthly_closure_year_gte_2000'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='monthly_closure_version_gt_0')],
            },
        ),
    ]
