# Generated by Django 5.2.5 on 2026-08-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monthlyclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_registers', to=settings.AUTH_USER_MODEL),
        ),
    ]
