# Generated by Django 5.2.5 on 2026-08-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cashregister_opened_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtssummary',
            name='business',
        ),
        migrations.RemoveField(
            model_name='inventorysummary',
            name='business',
        ),
        migrations.RemoveField(
            model_name='inventorysummary',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorysummary',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='paymentssummary',
            name='business',
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='business',
        ),
        migrations.RemoveField(
            model_name='supplierssummary',
            name='business',
        ),
        migrations.RemoveField(
            model_name='supplierssummary',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='CustomersSummary',
        ),
        migrations.DeleteModel(
            name='DebtsSummary',
        ),
        migrations.DeleteModel(
            name='InventorySummary',
        ),
        migrations.DeleteModel(
            name='PaymentsSummary',
        ),
        migrations.DeleteModel(
            name='SalesSummary',
        ),
        migrations.DeleteModel(
            name='SuppliersSummary',
        ),
    ]
